=== gosia4/XML-report-semester-III/sites/5/xmlscheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="wypGier"
           attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:wypozyczalniaGier="wypGier">
		   


    <xs:element name="wypozyczalniaGier" type="wypozyczalniaGier:wypGierTyp"/>


    <xs:complexType name="wypGierTyp">
        <xs:sequence>
            <xs:element name="dataStworzenia" type="wypozyczalniaGier:dataStworzeniaTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="gatunki" type="wypozyczalniaGier:gatunkiTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="daneWypozyczalniGier" type="wypozyczalniaGier:daneWypozyczalniGierTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="gry" type="wypozyczalniaGier:gryType" minOccurs="1" maxOccurs="1">
                <xs:key name="id">
                    <xs:selector xpath="gatunki/*"/>
                    <xs:field xpath="@rodzaj" />
                </xs:key>
                <xs:keyref name="id_odniesienie" refer="wypozyczalniaGier:id">
                    <xs:selector xpath="gry/gra/*"/>
                    <xs:field xpath="@rodzaj"/>
                </xs:keyref>
            </xs:element>
            <xs:element name="autorDokumentu" type="wypozyczalniaGier:autorDokumentuTyp" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dataStworzeniaTyp">
            <xs:attribute name="data" type="xs:date" />
    </xs:complexType>

    <!--GATUNKI TYP-->
    <xs:complexType name="gatunkiTyp">
        <xs:sequence>
            <xs:element name="gatunek" type="wypozyczalniaGier:gatunekTyp" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
        <!--GATUNEK TYP -->
        <xs:complexType name="gatunekTyp">
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="typ" type="wypozyczalniaGier:typTyp"/> <!-- maslo maslane -->
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>


    <xs:simpleType name="typTyp">           <!-- Typ dla atrybutu typ gatunków gier (3 literki)-->
        <xs:restriction base="xs:string">
            <xs:length value="3"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- KO -->

    <!--DANE WYPOZYCZALNI GIER TYP-->
    <xs:complexType name="daneWypozyczalniGierTyp">
        <xs:sequence>
            <xs:element name="wlasciciel" type="wypozyczalniaGier:wlascicielTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="miasto" type="wypozyczalniaGier:miastoTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="ulica" type="wypozyczalniaGier:ulicaTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="kodPocztowy" type="wypozyczalniaGier:kodPocztowyTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="telefon" type="wypozyczalniaGier:telefonTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="NIP" type="wypozyczalniaGier:nipTyp" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>


    <!--TYPY DANYCH W WYPOZYCZALNI-->
    <xs:simpleType name="wlascicielTyp">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="miastoTyp">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ulicaTyp">
        <xs:restriction base="xs:string">
            <xs:minLength value="5"/>
            <xs:maxLength value="120"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="kodPocztowyTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9]-[0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefonTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nipTyp">
        <xs:restriction base="xs:string">
            <xs:length value="13"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- KO -->

    <!--GRY TYP -->
    <xs:complexType name="gryType">
        <xs:sequence>
            <xs:element name="gra" type="wypozyczalniaGier:graTyp" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!--KO -->

    <!-- GRA TYP -->
    <xs:complexType name="graTyp">
        <xs:sequence>
            <xs:element name="tytul" type="wypozyczalniaGier:tytulTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="producent" type="wypozyczalniaGier:producentTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="wydawca" type="wypozyczalniaGier:wydawcaTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="dystrybutor" type="wypozyczalniaGier:dystrybutorTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="rokWydania" type="wypozyczalniaGier:rokWydaniaTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="cena" type="wypozyczalniaGier:cenaTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="czyWypozyczona" type="wypozyczalniaGier:czyWypozyczonaType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="PEGI" type="wypozyczalniaGier:PEGITyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="platforma" type="wypozyczalniaGier:platformaTyp" minOccurs="1" maxOccurs="1"/>
            <xs:element name="jezyk" type="wypozyczalniaGier:jezykTyp" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attributeGroup ref="wypozyczalniaGier:grupaatrybutow"/>
    </xs:complexType>

    <!--- Grupa Typy atrybutów -->
    <xs:attributeGroup name="grupaatrybutow">
        <xs:attribute name="ID" type="wypozyczalniaGier:IDType" use="required"/>
        <xs:attribute name="gatunek" type="wypozyczalniaGier:gatTyp" use="required"/>
    </xs:attributeGroup>


    <xs:simpleType name="IDType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="gatTyp">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>


    <!--- Typy dla gry -->
    <xs:simpleType name="tytulTyp">
        <xs:list itemType="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="producentTyp">
        <xs:list itemType="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="wydawcaTyp">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dystrybutorTyp">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="rokWydaniaTyp">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1900"/>
            <xs:maxExclusive value="2030"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cenaTyp">
        <xs:simpleContent>
            <xs:extension base="xs:float">
                <xs:attribute name="waluta" type="wypozyczalniaGier:walutaTyp" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="walutaTyp">
        <xs:restriction base="xs:token">
            <xs:enumeration value="PLN"/>
            <xs:enumeration value="EURO"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="czyWypozyczonaType">
        <xs:restriction base="xs:string">
            <xs:pattern value="NIE|TAK" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PEGITyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9][1-9]?\+|Każdy" />
            <xs:minLength value="0"/>
            <xs:maxLength value="6"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="platformaTyp">
        <xs:restriction base="xs:token">
            <xs:enumeration value="Windows" />
            <xs:enumeration value="Android" />
            <xs:enumeration value="Linux" />
            <xs:enumeration value="Nintendo Switch" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="jezykTyp">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>
<!--KO-->

<!-- AUTOR DOKUMENTU TYP -->
<xs:complexType name="autorDokumentuTyp">
    <xs:group ref="wypozyczalniaGier:grupatrybutowautora"/>
</xs:complexType>

<xs:group name="grupatrybutowautora">
    <xs:sequence>
        <xs:element name="imie" type="wypozyczalniaGier:imieTyp" minOccurs="1" maxOccurs="1"/>
        <xs:element name="nazwisko" type="wypozyczalniaGier:nazwiskoTyp" minOccurs="1" maxOccurs="1"/>
        <xs:element name="numerIndeksu" type="wypozyczalniaGier:numerIndeksuTyp" minOccurs="1" maxOccurs="1"/>
        <xs:element name="grupaLaboratoryjna" type="wypozyczalniaGier:grupaLaboratoryjnaTyp" minOccurs="1" maxOccurs="1"/>
        <xs:element name="mail" type="wypozyczalniaGier:mailTyp" minOccurs="1" maxOccurs="1"/>
        <xs:element name="dataOstatniejAktualizacji" type="xs:date" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:group>

<xs:simpleType name="imieTyp">
    <xs:restriction base="xs:string">
        <xs:minLength value="2"/>
        <xs:maxLength value="15"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="nazwiskoTyp">
    <xs:restriction base="xs:string">
        <xs:minLength value="3"/>
        <xs:maxLength value="15"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="numerIndeksuTyp">
    <xs:restriction base="xs:positiveInteger">
        <xs:pattern value="[0-9]{6}"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="mailTyp">
    <xs:restriction base="xs:string">
        <xs:pattern value="\d{6}@edu.p.lodz.pl|\d{6}@.p.lodz.pl" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="grupaLaboratoryjnaTyp">
    <xs:union>
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:pattern value="[0-6]-[0-6]"/>
            </xs:restriction>
        </xs:simpleType>
        <xs:simpleType>
            <xs:restriction base="xs:token">
                <xs:enumeration value="1-1"/>
                <xs:enumeration value="1-2"/>
                <xs:enumeration value="2-1"/>
                <xs:enumeration value="2-2"/>
                <xs:enumeration value="3-1"/>
                <xs:enumeration value="3-2"/>
                <xs:enumeration value="4-1"/>
                <xs:enumeration value="4-2"/>
                <xs:enumeration value="5-1"/>
                <xs:enumeration value="5-2"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:union>
</xs:simpleType>

<!--KO-->

</xs:schema>

=== gosia4/XML-report-semester-III/sites/5/games.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="style.css" ?>
<wypozyczalniaGier	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="wypGier xmlscheme.xsd" xmlns="wypGier">

	<dataStworzenia data="2022-12-10"/>
  
	<gatunki>
		<gatunek typ="ZRE">zrecznosciowe</gatunek><!--String-->
		<gatunek typ="PRZ">przygodowe</gatunek><!--String-->
		<gatunek typ="FAB">fabularne</gatunek><!--String-->
		<gatunek typ="STR">strategiczne</gatunek><!--String-->
		<gatunek typ="SUR">survival</gatunek><!--String-->
		<gatunek typ="PLA">platformowe</gatunek><!--String-->
		<gatunek typ="LOG">logiczne</gatunek><!--String-->
		<gatunek typ="EDU">edukacyjne</gatunek><!--String-->
	</gatunki>

	<daneWypozyczalniGier>
		<wlasciciel>Jan Kowalski</wlasciciel><!--String-->
		<miasto>Lodz</miasto><!--String-->
		<ulica>Nowa 13</ulica><!--String-->
		<kodPocztowy>11-002</kodPocztowy><!--Kod pocztowy-->
		<telefon>123-034-933</telefon><!--Telefon-->
		<NIP>123 45 67 819</NIP><!--String-->
	</daneWypozyczalniGier>
	
	<gry>
		<gra ID="1" gatunek="FAB">
			<tytul>Baldur's Gate II</tytul><!--String-->
			<producent>Bio Ware</producent><!--String-->
			<wydawca>Interplay Entertainment</wydawca><!--String-->
			<dystrybutor>CD project</dystrybutor><!--String-->
			<rokWydania>2000</rokWydania><!--Liczba-->
			<cena waluta="PLN">24.99 </cena><!--Cena-->
			<czyWypozyczona>TAK</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>16+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
	
		
		<gra ID="2" gatunek="PLA">
			<tytul>Trine</tytul><!--String-->
			<producent>Frozenbyte</producent><!--String-->
			<wydawca>Nobilis</wydawca><!--String-->
			<dystrybutor>CD project</dystrybutor><!--String-->
			<rokWydania>2011</rokWydania><!--Liczba-->
			<cena waluta="EURO">20.99 </cena><!--Cena-->
			<czyWypozyczona>NIE</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>12+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
	
		
		<gra ID="3" gatunek="STR">
			<tytul>Twierdza</tytul><!--String-->
			<producent>Firefly Studios</producent><!--String-->
			<wydawca>Take-Two Interactive</wydawca><!--String-->
			<dystrybutor>Play-It</dystrybutor><!--String-->
			<rokWydania>2001</rokWydania><!--Liczba-->
			<cena waluta="PLN">34.99 </cena><!--Cena-->
			<czyWypozyczona>NIE</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>12+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
	
		<gra ID="4" gatunek="STR">
			<tytul>Orcs Must Die!</tytul><!--String-->
			<producent>Robot Entertainment</producent><!--String-->
			<wydawca>Robot Entertainment</wydawca><!--String-->
			<dystrybutor>Robot Entertainment</dystrybutor><!--String-->
			<rokWydania>2011</rokWydania><!--Liczba-->
			<cena waluta="PLN">54.99 </cena><!--Cena-->
			<czyWypozyczona>TAK</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>12+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
		
		<gra ID="5" gatunek="SUR">
			<tytul>Ark: Survival Evolved</tytul><!--String-->
			<producent>Studio Wildcard</producent><!--String-->
			<wydawca>Studio Wildcard</wydawca><!--String-->
			<dystrybutor>Studio Wildcard</dystrybutor><!--String-->
			<rokWydania>2017</rokWydania><!--Liczba-->
			<cena waluta="EURO">111.99 </cena><!--Cena-->
			<czyWypozyczona>NIE</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>16+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Angielski</jezyk><!--String-->
		</gra>
		
		
		<gra ID="6" gatunek="PRZ">
			<tytul>Subnautica</tytul><!--String-->
			<producent>Unknown Worlds Entertainment</producent><!--String-->
			<wydawca>Unknown Worlds Entertainment</wydawca><!--String-->
			<dystrybutor>Unknown Worlds Entertainment</dystrybutor><!--String-->
			<rokWydania>2018</rokWydania><!--Liczba-->
			<cena waluta="PLN">89.99 </cena><!--Cena-->
			<czyWypozyczona>TAK</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>7+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Angielski</jezyk><!--String-->
		</gra>
		
		<gra ID="7" gatunek="LOG">
			<tytul>Hearthstone</tytul><!--String-->
			<producent>Blizzard Entertainment</producent><!--String-->
			<wydawca>Blizzard Entertainment</wydawca><!--String-->
			<dystrybutor>Blizzard Entertainment</dystrybutor><!--String-->
			<rokWydania>2014</rokWydania><!--Liczba-->
			<cena waluta="PLN">10.00 </cena><!--Cena-->
			<czyWypozyczona>TAK</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>7+</PEGI><!--String-->
			<platforma>Android</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
		
		<gra ID="8" gatunek="EDU">
			<tytul>Journeys</tytul><!--String-->
			<producent>A new studio</producent><!--String-->
			<wydawca>Microsoft</wydawca><!--String-->
			<dystrybutor>Microsoft</dystrybutor><!--String-->
			<rokWydania>2015</rokWydania><!--Liczba-->
			<cena waluta="PLN">16.00 </cena><!--Cena-->
			<czyWypozyczona>TAK</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>7+</PEGI><!--String-->
			<platforma>Linux</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Angielski</jezyk><!--String-->
		</gra>
		
		<gra ID="9" gatunek="PLA">
			<tytul>Ori and the blind forest</tytul><!--String-->
			<producent>Moon Studios</producent><!--String-->
			<wydawca>Microsoft</wydawca><!--String-->
			<dystrybutor>Microsoft</dystrybutor><!--String-->
			<rokWydania>2015</rokWydania><!--Liczba-->
			<cena waluta="EURO">49.99 </cena><!--Cena-->
			<czyWypozyczona>TAK</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>7+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Angielski</jezyk><!--String-->
		</gra>
		
		<gra ID="10" gatunek="FAB">
			<tytul>Gothic</tytul><!--String-->
			<producent>Piranha Bytes </producent><!--String-->
			<wydawca>JoWooD Entertainment</wydawca><!--String-->
			<dystrybutor>cdp.pl</dystrybutor><!--String-->
			<rokWydania>2001</rokWydania><!--Liczba-->
			<cena waluta="PLN">19.99 </cena><!--Cena-->
			<czyWypozyczona>TAK</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>12+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
		
		<gra ID="11" gatunek="PLA">
			<tytul>Captain Claw</tytul><!--String-->
			<producent>Monolith Productions</producent><!--String-->
			<wydawca>Monolith Productions</wydawca><!--String-->
			<dystrybutor>Monolith Productions</dystrybutor><!--String-->
			<rokWydania>1997</rokWydania><!--Liczba-->
			<cena waluta="PLN">9.99 </cena><!--Cena-->
			<czyWypozyczona>NIE</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>Każdy</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Angielski</jezyk><!--String-->
		</gra>
		
		<gra ID="12" gatunek="LOG">
			<tytul>Puzzle Quest: The Legend Returns</tytul><!--String-->
			<producent>Infinity Plus 2 </producent><!--String-->
			<wydawca>D3 Go!</wydawca><!--String-->
			<dystrybutor>	D3 Go!</dystrybutor><!--String-->
			<rokWydania>2019</rokWydania><!--Liczba-->
			<cena waluta="PLN">99.99 </cena><!--Cena-->
			<czyWypozyczona>NIE</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>7+</PEGI><!--String-->
			<platforma>Nintendo Switch</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
		
		<gra ID="13" gatunek="ZRE">
			<tytul>Vampire Survivors</tytul><!--String-->
			<producent>Luca Galante</producent><!--String-->
			<wydawca>Luca Galante</wydawca><!--String-->
			<dystrybutor>Luca Galante</dystrybutor><!--String-->
			<rokWydania>2021</rokWydania><!--Liczba-->
			<cena waluta="PLN">39.99 </cena><!--Cena-->
			<czyWypozyczona>NIE</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>12+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
		
		<gra ID="14" gatunek="STR">
			<tytul>Warcraft 3</tytul><!--String-->
			<producent>Blizzard Entertainment</producent><!--String-->
			<wydawca>Blizzard Entertainment</wydawca><!--String-->
			<dystrybutor>Blizzard Entertainment</dystrybutor><!--String-->
			<rokWydania>2003</rokWydania><!--Liczba-->
			<cena waluta="PLN">89.99 </cena><!--Cena-->
			<czyWypozyczona>TAK</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>12+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
		
		<gra ID="15" gatunek="FAB">
			<tytul>Warcraft III: Refunded</tytul><!--String-->
			<producent>Blizzard Entertainment</producent><!--String-->
			<wydawca>Blizzard Entertainment</wydawca><!--String-->
			<dystrybutor>Blizzard Entertainment</dystrybutor><!--String-->
			<rokWydania>2020</rokWydania><!--Liczba-->
			<cena waluta="PLN">99.99 </cena><!--Cena-->
			<czyWypozyczona>NIE</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>12+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Polski</jezyk><!--String-->
		</gra>
		
		<gra ID="16" gatunek="FAB">
			<tytul>Rust</tytul><!--String-->
			<producent>Facepunch Studios</producent><!--String-->
			<wydawca>Facepunch Studios</wydawca><!--String-->
			<dystrybutor>Steam</dystrybutor><!--String-->
			<rokWydania>2013</rokWydania><!--Liczba-->
			<cena waluta="PLN">69.99 </cena><!--Cena-->
			<czyWypozyczona>TAK</czyWypozyczona><!--Wartość Logiczna-->
			<PEGI>16+</PEGI><!--String-->
			<platforma>Windows</platforma><!--Typ Wyliczeniowy-->
			<jezyk>Angielski</jezyk><!--String-->
		</gra>
		
		<gra ID="17" gatunek="LOG">
			<tytul>2048</tytul><!--String-->
			<producent>Gabriele Cirulli</producent><!--String-->
			<wydawca>Gabriele Cirulli </wydawca><!--String-->
			<dystrybutor>Gabriele Cirulli </dystrybutor><!--String-->
